[package]
name = "ktc-parity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "ktc-parity"
path = "src/main.rs"

[dependencies]
ktc-span    = { workspace = true }
ktc-lexer   = { workspace = true }
ktc-parser  = { workspace = true }
ktc-interp  = { workspace = true }
ktc-runtime = { workspace = true }

[lints]
workspace = true
