//! Emit Rust source for the `ktc-stdlib` generated registry.

use std::collections::HashSet;
use std::fs;
use std::path::Path;

use crate::parse::{Decl, DeclKind};
use crate::walk::FileDecls;

const MOD_RS: &str = "//! Generated by `ktc-stdlib-gen`. Do not edit by hand.
//!
//! Run `cargo run -p ktc-stdlib-gen -- build` to regenerate.

#![allow(clippy::all)]
#![allow(clippy::pedantic)]

mod symbols;

pub use symbols::STDLIB_SYMBOLS;
";

pub fn emit_generated(out_dir: &Path, files: &[FileDecls]) -> std::io::Result<usize> {
    fs::create_dir_all(out_dir)?;
    fs::write(out_dir.join("mod.rs"), MOD_RS)?;

    let mut body = String::new();
    body.push_str("//! Generated by `ktc-stdlib-gen`. Do not edit by hand.\n\n");
    body.push_str("use crate::{Modifiers, SourceLoc, SymbolEntry, SymbolKind};\n\n");
    body.push_str("pub static STDLIB_SYMBOLS: &[SymbolEntry] = &[\n");

    let mut seen: HashSet<String> = HashSet::new();
    let mut count = 0usize;
    for f in files {
        for d in &f.decls {
            // Build a uniqueness key: fqn + signature shape (so overloads
            // don't collide).
            let key = format!("{}|{}|{:?}|{}", d.fqn, d.signature, d.kind, f.rel_path);
            if !seen.insert(key) {
                continue;
            }
            count += 1;
            emit_entry(&mut body, d, &f.rel_path);
        }
    }
    body.push_str("];\n");
    fs::write(out_dir.join("symbols.rs"), body)?;
    Ok(count)
}

fn emit_entry(out: &mut String, d: &Decl, rel: &str) {
    let kind = match d.kind {
        DeclKind::Function => "SymbolKind::Function",
        DeclKind::Property => "SymbolKind::Property",
        DeclKind::Class => "SymbolKind::Class",
        DeclKind::Interface => "SymbolKind::Interface",
        DeclKind::Object => "SymbolKind::Object",
        DeclKind::TypeAlias => "SymbolKind::TypeAlias",
    };
    let package = d
        .fqn
        .rsplit_once('.')
        .map(|(p, _)| p)
        .unwrap_or("")
        .to_string();
    let recv = match &d.receiver {
        Some(r) => format!("Some({})", escape_str(r)),
        None => "None".to_string(),
    };
    out.push_str("    SymbolEntry {\n");
    out.push_str(&format!("        fqn: {},\n", escape_str(&d.fqn)));
    out.push_str(&format!("        package: {},\n", escape_str(&package)));
    out.push_str(&format!("        name: {},\n", escape_str(&d.name)));
    out.push_str(&format!("        kind: {},\n", kind));
    out.push_str(&format!("        receiver: {},\n", recv));
    out.push_str(&format!("        signature: {},\n", escape_str(&d.signature)));
    if d.param_names.is_empty() {
        out.push_str("        param_names: &[],\n");
    } else {
        out.push_str("        param_names: &[");
        for (i, n) in d.param_names.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&escape_str(n));
        }
        out.push_str("],\n");
    }
    out.push_str(&format!("        modifiers: Modifiers({}),\n", d.modifiers));
    out.push_str(&format!(
        "        source: SourceLoc {{ path: {}, line: {}, column: {} }},\n",
        escape_str(rel),
        d.line,
        d.column
    ));
    out.push_str("        impl_fn: None,\n");
    out.push_str("    },\n");
}

fn escape_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
