//! The C file of a native build, in the order a C compiler accepts it: the
//! runtime's declarations, the bodies, the dispatchers, the singletons, the
//! description of the program the runtime builds its module from, and
//! `main`.

const std = @import("std");
const ir = @import("ir");
const sema = @import("sema");

const ctype = @import("ctype.zig");
const program = @import("program.zig");
const cfunc = @import("cfunc.zig");
const sig_mod = @import("sig.zig");
const rt = @import("rt_abi.zig");

const Ty = ctype.Ty;
const Program = program.Program;
const Writer = std.Io.Writer;
const FuncId = ir.FuncId;
const ClassId = ir.ClassId;
const NativeId = ir.NativeId;
const MethodSlotId = ir.MethodSlotId;
const Error = cfunc.Error;
const Raise = rt.Raise;
const NONE = ir.resolved.NONE;

pub fn write(p: *Program, w: *Writer, src_path: []const u8) Error!void {
    try w.print(
        \\/* Generated by `klio transpile --native {s}`. Do not edit.
        \\ * The program itself: every function is a C function over the klio
        \\ * runtime's values; no image is loaded and no interpreter runs it.
        \\ * Build: zig cc -O2 <this file> -I<include> -L<lib> -lklio_rt -lzstd */
        \\#include <stdio.h>
        \\#include <stdint.h>
        \\#include <stdlib.h>
        \\#include <string.h>
        \\#include <math.h>
        \\#include <setjmp.h>
        \\#include <klio_rt.h>
        \\
        \\
    , .{src_path});
    var callbacks = try collectCallbacks(p);
    try writeMachinery(w);
    try writeDeclarations(p, w);
    try writeStorage(p, w);
    for (p.bodies.items) |*b| try cfunc.writeBody(p, w, b);
    try writeClosureMembers(p, w);
    try writeDispatchers(p, w);
    try writeCallValue(p, w);
    try writeSingletons(p, w);
    try writeCallbacks(p, w, &callbacks);
    try writeClasses(p, w);
    try writeProgram(p, w, &callbacks);
    try writeMain(p, w);
}

fn writeMachinery(w: *Writer) Error!void {
    try w.writeAll(
        \\/* A try region. `setjmp` has to be called in the frame that catches,
        \\ * so the handler stack lives here rather than in the runtime. */
        \\typedef struct klio_try { struct klio_try *prev; jmp_buf jb; } klio_try;
        \\static klio_try *klio_try_top = 0;
        \\static klio_value klio_in_flight;
        \\static void klio_try_arm(klio_try *t) { t->prev = klio_try_top; klio_try_top = t; }
        \\static void klio_try_pop(klio_try *t) {
        \\  for (klio_try *q = klio_try_top; q; q = q->prev) if (q == t) { klio_try_top = t->prev; return; }
        \\}
        \\/* An exception the runtime raises: built through the class the program
        \\ * registered for it and thrown into the program. */
        \\#define kraise klio_r_raise
        \\KLIO_NORETURN static void kthrow(klio_value e) {
        \\  if (klio_nat_is_null(e)) klio_r_raise(0u, klio_nat_null());
        \\  klio_in_flight = e;
        \\  if (klio_try_top) longjmp(klio_try_top->jb, 1);
        \\  klio_r_uncaught(e);
        \\}
        \\
        \\
    );
}

fn writeDeclarations(p: *Program, w: *Writer) Error!void {
    for (p.bodies.items) |*b| {
        try cfunc.writeProto(w, b);
        try w.writeAll(";\n");
    }
    for (p.rc.slots.items) |slot| try writeDispatcherProto(p, w, slot);
    try w.writeAll("static klio_value kcall(klio_value f, const klio_value *a, uint32_t n);\n");
    for (p.objects.items) |c| try w.print("static klio_value ko_{d}(void);\n", .{c.int()});
    for (p.units.items, 0..) |_, i| try w.print("static void ku_{d}(void);\n", .{i});
    for (p.closures.items) |cc| if (cc.kind == .lambda and cc.n_caps == 0) try w.print("static klio_value klam_{d}(void);\n", .{cc.id});
    try w.writeAll("\n");
}

fn writeDispatcherProto(p: *Program, w: *Writer, slot: MethodSlotId) Error!void {
    const sg = try p.sigs.of(FuncId.from(slot.int()));
    try w.print("static {s} kv_{d}(", .{ sg.ret.cName(), slot.int() });
    for (sg.params, 0..) |t, i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{s} a{d}", .{ t.cName(), i });
    }
    if (sg.params.len == 0) try w.writeAll("void");
    try w.writeAll(");\n");
}

/// Statics, init-unit states, singletons and non-capturing closures, in a
/// frame published for the program's life.
fn writeStorage(p: *Program, w: *Writer) Error!void {
    const n_roots = p.statics.items.len + p.objects.items.len + p.closures.items.len + 2;
    try w.print("static klio_value KROOT[{d}];\nstatic klio_nat_frame KROOTF;\n", .{n_roots});
    try w.print("#define KG (KROOT + 2)\n#define KO (KROOT + {d})\n#define KL (KROOT + {d})\n", .{ 2 + p.statics.items.len, 2 + p.statics.items.len + p.objects.items.len });
    if (p.units.items.len != 0) try w.print("static uint8_t KU[{d}];\n", .{p.units.items.len});
    if (p.objects.items.len != 0) try w.print("static uint8_t KOS[{d}];\n", .{p.objects.items.len});
    try w.writeAll("\n");
}

/// Which `Any` member of a closure a slot is.
const ClosureMember = enum { equals, hash, to_string };

fn closureMemberOf(p: *const Program, slot: MethodSlotId) ?ClosureMember {
    const h = &p.r.host_class;
    if (h.equals_slot) |s| if (s == slot) return .equals;
    if (h.hash_code_slot) |s| if (s == slot) return .hash;
    if (h.to_string_slot) |s| if (s == slot) return .to_string;
    return null;
}

/// A closure answers `equals`, `hashCode` and `toString` by what it is, as
/// the VM's closures do: a reference by its target and its bound receiver,
/// a lambda by identity, and its text as kotlinc prints it.
fn writeClosureMembers(p: *Program, w: *Writer) Error!void {
    for (p.closures.items) |cc| {
        const func = p.m.funcById(cc.body) orelse continue;
        const kind: ir.resolved.Callable = if (cc.kind == .function_ref) .{ .function_ref = cc.target } else .lambda;
        const text = try ir.eval.resolved_ops.closureText(p.a, p.m, .{ .id = 0, .func = func, .module = p.m, .kind = kind });
        try w.print("static klio_value kclo_eq_{d}(klio_value self, klio_value other) {{\n", .{cc.id});
        try w.print("  if (klio_nat_bool(klio_r_binop({d}u, self, other))) return klio_nat_box_bool(1);\n", .{@intFromEnum(ir.BinOp.IdentEq)});
        if (cc.kind == .function_ref) {
            // One adapter per target and shape, so one class is one callable.
            try w.print("  if (klio_r_class_of(other) != {d}u) return klio_nat_box_bool(0);\n", .{cc.id});
            var i: u32 = 0;
            while (i < cc.n_caps) : (i += 1) {
                try w.print("  if (!klio_r_equals(klio_r_get(self, {d}), klio_r_get(other, {d}))) return klio_nat_box_bool(0);\n", .{ i, i });
            }
            try w.writeAll("  return klio_nat_box_bool(1);\n}\n");
            try w.print("static klio_value kclo_hash_{d}(klio_value self) {{\n  uint32_t h = {d}u;\n", .{ cc.id, cc.target.int() & 0x7fffffff });
            i = 0;
            while (i < cc.n_caps) : (i += 1) try w.print("  h = h * 31u + (uint32_t)klio_r_hash_code(klio_r_get(self, {d}));\n", .{i});
            try w.writeAll("  (void)self;\n  return klio_nat_box_int((int32_t)h);\n}\n");
            try w.print("static klio_value kclo_str_{d}(klio_value self) {{\n  (void)self;\n  return klio_nat_string(", .{cc.id});
            try ctype.writeCString(w, text);
            try w.print(", {d});\n}}\n", .{text.len});
        } else {
            try w.writeAll("  return klio_nat_box_bool(0);\n}\n");
            try w.print("static klio_value kclo_hash_{d}(klio_value self) {{\n  return klio_nat_box_int(klio_r_identity_hash(self));\n}}\n", .{cc.id});
            // A lambda's text ends in its instance's hash.
            const stem = if (std.mem.findScalarLast(u8, text, '@')) |at| text[0..at] else text;
            try w.print("static klio_value kclo_str_{d}(klio_value self) {{\n  return klio_r_lambda_text(", .{cc.id});
            try ctype.writeCString(w, stem);
            try w.writeAll(", self);\n}\n");
        }
    }
    if (p.closures.items.len != 0) try w.writeAll("\n");
}

/// A virtual call: the implementation of the receiver's class, converted
/// to and from the root's signature.
fn writeDispatchers(p: *Program, w: *Writer) Error!void {
    for (p.rc.slots.items) |slot| {
        const root_id = FuncId.from(slot.int());
        const sg = try p.sigs.of(root_id);
        try w.print("/* {s} */\n", .{p.funcName(root_id)});
        try w.print("static {s} kv_{d}(", .{ sg.ret.cName(), slot.int() });
        for (sg.params, 0..) |t, i| {
            if (i != 0) try w.writeAll(", ");
            try w.print("{s} a{d}", .{ t.cName(), i });
        }
        if (sg.params.len == 0) try w.writeAll("void");
        try w.writeAll(") {\n");
        if (sg.params.len == 0 or sg.params[0] != .object) {
            p.refuse("the slot `{s}` has no receiver", .{p.funcName(root_id)});
            try w.writeAll("  abort();\n}\n");
            continue;
        }
        try w.writeAll("  switch (klio_r_class_of(a0)) {\n");
        var classes: std.ArrayList(ClassId) = .empty;
        try classes.appendSlice(p.a, p.rc.constructed.items);
        try classes.appendSlice(p.a, p.rc.hosts.items);
        var done: std.AutoHashMapUnmanaged(u32, void) = .empty;
        for (classes.items) |c| {
            if (done.contains(c.int())) continue;
            const t = p.rc.target(c, slot) orelse continue;
            // Every class this target serves shares one arm.
            try w.print("  case {d}u:", .{c.int()});
            try done.put(p.a, c.int(), {});
            for (classes.items) |c2| {
                if (done.contains(c2.int())) continue;
                const t2 = p.rc.target(c2, slot) orelse continue;
                if (t2 != t) continue;
                try w.print(" case {d}u:", .{c2.int()});
                try done.put(p.a, c2.int(), {});
            }
            try w.writeAll("\n    return ");
            try writeTargetCall(p, w, t, sg, "a");
            try w.writeAll(";\n");
        }
        // A closure answers its own `invoke`.
        for (p.closures.items) |cc| {
            if (!isInvokeSlot(p, slot, cc.arity)) continue;
            try w.print("  case {d}u: {{ klio_value ka[{d}] = {{", .{ cc.id, @max(cc.arity, 1) });
            var i: u32 = 0;
            while (i < cc.arity) : (i += 1) {
                if (i != 0) try w.writeAll(", ");
                try ctype.writeBox(w, sg.params[i + 1], try std.fmt.allocPrint(p.a, "a{d}", .{i + 1}));
            }
            if (cc.arity == 0) try w.writeAll("{0}");
            try w.writeAll("};\n    return ");
            try ctype.writeConv(w, .object, sg.ret, try std.fmt.allocPrint(p.a, "kcall(a0, ka, {d})", .{cc.arity}));
            try w.writeAll("; }\n");
        }
        if (closureMemberOf(p, slot)) |which| for (p.closures.items) |cc| {
            try w.print("  case {d}u: return ", .{cc.id});
            const call = switch (which) {
                .equals => blk: {
                    var aw: std.Io.Writer.Allocating = .init(p.a);
                    try ctype.writeBox(&aw.writer, if (sg.params.len > 1) sg.params[1] else .object, "a1");
                    break :blk try std.fmt.allocPrint(p.a, "kclo_eq_{d}(a0, {s})", .{ cc.id, aw.written() });
                },
                .hash => try std.fmt.allocPrint(p.a, "kclo_hash_{d}(a0)", .{cc.id}),
                .to_string => try std.fmt.allocPrint(p.a, "kclo_str_{d}(a0)", .{cc.id}),
            };
            try ctype.writeConv(w, .object, sg.ret, call);
            try w.writeAll(";\n");
        };
        try w.writeAll("  default: break;\n  }\n");
        try w.print("  if (klio_nat_is_null(a0)) kraise({d}u, klio_nat_null());\n", .{@intFromEnum(Raise.npe)});
        // A host value whose class leaves the slot open: the VM's
        // implementation of the slot's root.
        if (slot.int() < p.r.host_slot.len and p.r.host_slot[slot.int()] != .none) {
            const hn = p.r.host_slot[slot.int()];
            try w.print("  {{ klio_value ka[{d}] = {{", .{sg.params.len});
            for (sg.params, 0..) |t, i| {
                if (i != 0) try w.writeAll(", ");
                try ctype.writeBox(w, t, try std.fmt.allocPrint(p.a, "a{d}", .{i}));
            }
            try w.writeAll("};\n    return ");
            const call = try std.fmt.allocPrint(p.a, "klio_r_native_call({d}u, ka, {d})", .{ p.nativeIndex(hn), sg.params.len });
            try ctype.writeConv(w, .object, sg.ret, call);
            try w.writeAll("; }\n}\n\n");
            continue;
        }
        try w.writeAll("  klio_r_no_method(");
        try ctype.writeCString(w, p.funcName(root_id));
        try w.writeAll(");\n}\n\n");
    }
}

/// Argument `i` of a dispatcher: `a<i>` for its parameters, `ab[<i>]` for
/// an array of them.
fn argName(p: *Program, prefix: []const u8, i: usize) Error![]const u8 {
    if (std.mem.endsWith(u8, prefix, "[")) return std.fmt.allocPrint(p.a, "{s}{d}]", .{ prefix, i });
    return std.fmt.allocPrint(p.a, "{s}{d}", .{ prefix, i });
}

fn isInvokeSlot(p: *const Program, slot: MethodSlotId, arity: u32) bool {
    const h = &p.r.host_class;
    if (arity < h.invoke_slot.len and h.invoke_slot[arity] == slot) return true;
    if (arity < h.suspend_invoke_slot.len and h.suspend_invoke_slot[arity] == slot) return true;
    return false;
}

/// A call of target `t` from a dispatcher whose parameters `<prefix>i`
/// have the kinds `sg` gives, as an expression of `sg.ret`.
fn writeTargetCall(p: *Program, w: *Writer, t: FuncId, sg: sig_mod.Sig, prefix: []const u8) Error!void {
    if (p.nativeOf(t)) |n| {
        var call: std.Io.Writer.Allocating = .init(p.a);
        try call.writer.print("klio_r_native_call({d}u, (klio_value[]){{", .{p.nativeIndex(n)});
        for (sg.params, 0..) |pt, i| {
            if (i != 0) try call.writer.writeAll(", ");
            try ctype.writeBox(&call.writer, pt, try argName(p, prefix, i));
        }
        if (sg.params.len == 0) try call.writer.writeAll("{0}");
        try call.writer.print("}}, {d})", .{sg.params.len});
        try ctype.writeConv(w, .object, sg.ret, call.written());
        return;
    }
    const b = p.body(t) orelse {
        p.refuse("the implementation `{s}` is not compiled", .{p.funcName(t)});
        try w.writeAll("0");
        return;
    };
    if (b.sig.params.len != sg.params.len) {
        p.refuse("`{s}` takes {d} parameters where its root takes {d}", .{ p.funcName(t), b.sig.params.len, sg.params.len });
        try w.writeAll("0");
        return;
    }
    var call: std.Io.Writer.Allocating = .init(p.a);
    try call.writer.print("kf_{d}(", .{t.int()});
    for (sg.params, b.sig.params, 0..) |have, want, i| {
        if (i != 0) try call.writer.writeAll(", ");
        try ctype.writeConv(&call.writer, have, want, try argName(p, prefix, i));
    }
    try call.writer.writeAll(")");
    try ctype.writeConv(w, b.sig.ret, sg.ret, call.written());
}

/// A signature with every parameter and the result boxed.
fn boxedSig(p: *Program, sg: sig_mod.Sig) Error!sig_mod.Sig {
    var out = sg;
    const ps = try p.a.alloc(Ty, sg.params.len);
    @memset(ps, .object);
    out.params = ps;
    out.ret = .object;
    return out;
}

/// Calling a function value: a closure's body, or the `invoke` of an
/// instance of a class implementing a function type.
fn writeCallValue(p: *Program, w: *Writer) Error!void {
    try w.writeAll("static klio_value kcall(klio_value f, const klio_value *a, uint32_t n) {\n  (void)a; (void)n;\n  switch (klio_r_class_of(f)) {\n");
    for (p.closures.items) |cc| {
        const b = p.body(cc.body) orelse continue;
        try w.print("  case {d}u: if (n == {d}) return ", .{ cc.id, cc.arity });
        var call: std.Io.Writer.Allocating = .init(p.a);
        try call.writer.print("kf_{d}(f", .{cc.body.int()});
        for (b.sig.params, 0..) |pt, i| {
            try call.writer.writeAll(", ");
            try ctype.writeConv(&call.writer, .object, pt, try std.fmt.allocPrint(p.a, "a[{d}]", .{i}));
        }
        try call.writer.writeAll(")");
        try ctype.writeBox(w, b.sig.ret, call.written());
        try w.writeAll("; break;\n");
    }
    // Instances of a class implementing `invoke` of a function type.
    const h = &p.r.host_class;
    for (p.rc.constructed.items) |c| {
        for (h.invoke_slot, 0..) |slot, arity| {
            const t = p.rc.target(c, slot) orelse continue;
            if (p.body(t) == null and p.nativeOf(t) == null) continue;
            try w.print("  case {d}u: if (n == {d}) {{\n", .{ c.int(), arity });
            const sg = try p.sigs.of(FuncId.from(slot.int()));
            var i: u32 = 0;
            try w.writeAll("    klio_value ab[] = {f");
            while (i < arity) : (i += 1) try w.print(", a[{d}]", .{i});
            try w.writeAll("};\n    (void)ab;\n    return ");
            try writeTargetCall(p, w, t, try boxedSig(p, sg), "ab[");
            try w.writeAll(";\n  }\n  break;\n");
            break;
        }
    }
    try w.print("  default: break;\n  }}\n  if (klio_nat_is_null(f)) kraise({d}u, klio_nat_null());\n  klio_r_no_method(\"invoke\");\n}}\n\n", .{@intFromEnum(Raise.npe)});
}

/// Objects and companions, made on first use; init units, run on the first
/// touch of a static they write; non-capturing closures, one instance each.
fn writeSingletons(p: *Program, w: *Writer) Error!void {
    for (p.objects.items, 0..) |c, i| {
        const ctor = p.r.classes[c.int()].object_ctor;
        try w.print("static klio_value ko_{d}(void) {{\n  static const char kname[] = ", .{c.int()});
        try ctype.writeCString(w, p.r.classes[c.int()].init_name);
        try w.print(";\n  if (KOS[{d}] == 1 || KOS[{d}] == 2) return KO[{d}];\n", .{ i, i, i });
        try w.print("  if (KOS[{d}] == 3) klio_r_init_failed(klio_nat_null(), kname);\n", .{i});
        try w.print("  KOS[{d}] = 1;\n  KO[{d}] = klio_r_new({d}u);\n", .{ i, i, c.int() });
        try w.writeAll("  { klio_try t; klio_nat_frame *m = klio_nat_frame_mark(); klio_try_arm(&t);\n");
        try w.print("    if (setjmp(t.jb) != 0) {{ klio_nat_frame_restore(m); klio_try_top = t.prev; KO[{d}] = klio_nat_null(); KOS[{d}] = 3; klio_r_init_failed(klio_in_flight, kname); }}\n", .{ i, i });
        if (ctor != ir.NO_FUNC) {
            const b = p.body(FuncId.from(ctor)) orelse {
                p.refuse("the object constructor `{s}` is not compiled", .{p.funcName(FuncId.from(ctor))});
                continue;
            };
            try w.print("    (void)kf_{d}(", .{ctor});
            try ctype.writeConv(w, .object, if (b.sig.params.len != 0) b.sig.params[0] else .object, try std.fmt.allocPrint(p.a, "KO[{d}]", .{i}));
            try w.writeAll(");\n");
        }
        try w.print("    klio_try_pop(&t); }}\n  KOS[{d}] = 2;\n  return KO[{d}];\n}}\n\n", .{ i, i });
    }
    for (p.units.items, 0..) |unit, i| {
        const f = p.r.init_units[unit].func;
        try w.print("static void ku_{d}(void) {{\n  static const char kname[] = ", .{i});
        try ctype.writeCString(w, p.r.init_units[unit].name);
        try w.print(";\n  if (KU[{d}] == 1 || KU[{d}] == 2) return;\n  if (KU[{d}] == 3) klio_r_init_failed(klio_nat_null(), kname);\n  KU[{d}] = 1;\n", .{ i, i, i, i });
        try w.writeAll("  { klio_try t; klio_nat_frame *m = klio_nat_frame_mark(); klio_try_arm(&t);\n");
        try w.print("    if (setjmp(t.jb) != 0) {{ klio_nat_frame_restore(m); klio_try_top = t.prev; KU[{d}] = 3; klio_r_init_failed(klio_in_flight, kname); }}\n", .{i});
        try w.print("    (void)kf_{d}();\n    klio_try_pop(&t); }}\n  KU[{d}] = 2;\n}}\n\n", .{ f.int(), i });
    }
    var li: usize = 0;
    for (p.closures.items) |cc| {
        if (cc.kind != .lambda or cc.n_caps != 0) continue;
        try w.print("static klio_value klam_{d}(void) {{\n  if (klio_nat_is_null(KL[{d}])) KL[{d}] = klio_r_new({d}u);\n  return KL[{d}];\n}}\n\n", .{ cc.id, li, li, cc.id, li });
        li += 1;
    }
}

// ---------------------------------------------------------------------------
// The functions the host calls back

/// A function the runtime's module lets the host call: a compiled body, a
/// native, or a closure class's `invoke`.
const Callback = union(enum) {
    compiled: FuncId,
    native: NativeId,
    invoke: u32,
    /// A closure class's `equals`, `hashCode` or `toString`.
    closure: struct { cls: u32, which: ClosureMember },
};

const Dispatch = struct { cls: u32, slot: u32, entry: u32 };
const HostRaised = struct { fqn: []const u8, raised: ir.resolved.Raised };

const Callbacks = struct {
    entries: std.ArrayList(Callback) = .empty,
    dispatch: std.ArrayList(Dispatch) = .empty,
    /// One per `Raise`.
    fixed: [9]?ir.resolved.Raised = @splat(null),
    match_groups: ?ir.resolved.ClassCtor = null,
    by_fqn: std.ArrayList(HostRaised) = .empty,

    fn entryOf(self: *Callbacks, p: *Program, cb: Callback) Error!u32 {
        for (self.entries.items, 0..) |e, i| {
            if (std.meta.eql(e, cb)) return @intCast(i);
        }
        try self.entries.append(p.a, cb);
        return @intCast(self.entries.items.len - 1);
    }
};

/// What the host may call back into: each constructed class's
/// implementations of the well-known members natives call back through, a
/// closure class's `invoke`, the constructors of the exceptions the runtime
/// raises into a `catch` of the program, and of the base classes it builds.
fn collectCallbacks(p: *Program) Error!Callbacks {
    var cbs: Callbacks = .{};
    for (p.rc.constructed.items) |c| {
        for (p.r.well_known.values) |wk| {
            const slot = wk orelse continue;
            const t = p.rc.target(c, slot) orelse continue;
            const cb: Callback = if (p.nativeOf(t)) |n| .{ .native = n } else if (p.body(t) != null) .{ .compiled = t } else continue;
            try cbs.dispatch.append(p.a, .{ .cls = c.int(), .slot = slot.int(), .entry = try cbs.entryOf(p, cb) });
        }
        // An instance of a class implementing a function type is invoked
        // through its `invoke`.
        for (p.r.host_class.invoke_slot) |slot| {
            const t = p.rc.target(c, slot) orelse continue;
            const cb: Callback = if (p.nativeOf(t)) |n| .{ .native = n } else if (p.body(t) != null) .{ .compiled = t } else continue;
            try cbs.dispatch.append(p.a, .{ .cls = c.int(), .slot = slot.int(), .entry = try cbs.entryOf(p, cb) });
        }
    }
    for (p.closures.items) |cc| {
        const h = &p.r.host_class;
        const members = [_]struct { ?MethodSlotId, ClosureMember }{ .{ h.equals_slot, .equals }, .{ h.hash_code_slot, .hash }, .{ h.to_string_slot, .to_string } };
        for (members) |mm| {
            const slot = mm[0] orelse continue;
            try cbs.dispatch.append(p.a, .{ .cls = cc.id, .slot = slot.int(), .entry = try cbs.entryOf(p, .{ .closure = .{ .cls = cc.id, .which = mm[1] } }) });
        }
        if (cc.arity >= h.invoke_slot.len) continue;
        try cbs.dispatch.append(p.a, .{ .cls = cc.id, .slot = h.invoke_slot[cc.arity].int(), .entry = try cbs.entryOf(p, .{ .invoke = cc.arity }) });
    }
    const e = &p.r.exceptions;
    const fixed = [_]?ir.resolved.Raised{ e.null_pointer, e.class_cast, e.arithmetic, e.uninitialized_property, e.index_out_of_bounds, e.array_index_out_of_bounds, e.string_index_out_of_bounds, p.r.base.init_failed, p.r.base.no_class_def };
    for (fixed, 0..) |x, k| {
        const raised = x orelse continue;
        if (!isRaisable(p, raised)) continue;
        _ = try cbs.entryOf(p, .{ .compiled = raised.ctor });
        cbs.fixed[k] = raised;
    }
    if (p.match_groups) |mg| if (p.body(mg.ctor) != null) {
        _ = try cbs.entryOf(p, .{ .compiled = mg.ctor });
        cbs.match_groups = mg;
    };
    for (p.rc.raisable_hosts.items) |hr| {
        if (!isRaisable(p, hr.raised)) continue;
        _ = try cbs.entryOf(p, .{ .compiled = hr.raised.ctor });
        try cbs.by_fqn.append(p.a, .{ .fqn = hr.key, .raised = hr.raised });
    }
    return cbs;
}

fn isRaisable(p: *const Program, raised: ir.resolved.Raised) bool {
    for (p.rc.raisable.items) |x| {
        if (x.class == raised.class and x.ctor == raised.ctor) return p.body(raised.ctor) != null;
    }
    return false;
}

/// The C function each compiled callback runs through: its arguments
/// boxed, its throw caught and handed back.
fn writeCallbacks(p: *Program, w: *Writer, cbs: *const Callbacks) Error!void {
    for (cbs.entries.items, 0..) |cb, i| {
        switch (cb) {
            .native => continue,
            .compiled => |f| {
                const b = p.body(f).?;
                try w.print("/* {s} */\nstatic int32_t kw_{d}(const klio_value *a, uint32_t n, klio_value *out) {{\n  (void)a; (void)n;\n", .{ p.funcName(f), i });
                try writeGuard(w);
                var call: std.Io.Writer.Allocating = .init(p.a);
                try call.writer.print("kf_{d}(", .{f.int()});
                if (b.closure) try call.writer.writeAll("klio_nat_null()");
                for (b.sig.params, 0..) |pt, k| {
                    if (k != 0 or b.closure) try call.writer.writeAll(", ");
                    try ctype.writeConv(&call.writer, .object, pt, try std.fmt.allocPrint(p.a, "a[{d}]", .{k}));
                }
                try call.writer.writeAll(")");
                try w.writeAll("  *out = ");
                try ctype.writeBox(w, b.sig.ret, call.written());
                try w.writeAll(";\n  klio_try_pop(&t);\n  return 0;\n}\n");
            },
            .invoke => |arity| {
                try w.print("static int32_t kw_{d}(const klio_value *a, uint32_t n, klio_value *out) {{\n  (void)n;\n", .{i});
                try writeGuard(w);
                try w.print("  *out = kcall(a[0], a + 1, {d});\n  klio_try_pop(&t);\n  return 0;\n}}\n", .{arity});
            },
            .closure => |c| {
                try w.print("static int32_t kw_{d}(const klio_value *a, uint32_t n, klio_value *out) {{\n  (void)n;\n", .{i});
                try writeGuard(w);
                switch (c.which) {
                    .equals => try w.print("  *out = kclo_eq_{d}(a[0], a[1]);\n", .{c.cls}),
                    .hash => try w.print("  *out = kclo_hash_{d}(a[0]);\n", .{c.cls}),
                    .to_string => try w.print("  *out = kclo_str_{d}(a[0]);\n", .{c.cls}),
                }
                try w.writeAll("  klio_try_pop(&t);\n  return 0;\n}\n");
            },
        }
    }
    try w.writeAll("\n");
}

fn writeGuard(w: *Writer) Error!void {
    try w.writeAll("  klio_try t; klio_nat_frame *m = klio_nat_frame_mark(); klio_try_arm(&t);\n");
    try w.writeAll("  if (setjmp(t.jb) != 0) { klio_nat_frame_restore(m); klio_try_top = t.prev; *out = klio_in_flight; return 1; }\n");
}

// ---------------------------------------------------------------------------
// The description of the program

/// Every class the program registers: its layout, its ancestors, the flags
/// the host's rendering and equality read.
fn writeClasses(p: *Program, w: *Writer) Error!void {
    for (p.classes.items) |c| {
        if (c >= p.r.classes.len) continue;
        const crt = &p.r.classes[c];
        const def = crt.def.asPtrConst();
        var slot_names: std.ArrayList([]const u8) = .empty;
        for (def.layout_slots) |ls| try slot_names.append(p.a, ls.name);
        try writeNameList(w, "KCN", c, slot_names.items);
        try w.print("static const uint8_t KCS_{d}[] = {{", .{c});
        for (crt.seeds, 0..) |s, i| {
            if (i != 0) try w.writeAll(", ");
            try w.print("{d}", .{@intFromEnum(s)});
        }
        if (crt.seeds.len == 0) try w.writeAll("0");
        try w.writeAll("};\n");
        const anc = try ancestorsOf(p, c);
        try writeIds(w, "KCA", c, anc.ids);
        try writeNameList(w, "KCAN", c, anc.names);
        var prim: std.ArrayList([]const u8) = .empty;
        var prim_mut: std.ArrayList(u8) = .empty;
        for (def.primary_params) |pp| {
            try prim.append(p.a, pp.name);
            try prim_mut.append(p.a, if (pp.property) |mutable| @as(u8, if (mutable) 2 else 1) else 0);
        }
        try writeNameList(w, "KCP", c, prim.items);
        try w.print("static const uint8_t KCPM_{d}[] = {{", .{c});
        for (prim_mut.items, 0..) |x, i| {
            if (i != 0) try w.writeAll(", ");
            try w.print("{d}", .{x});
        }
        if (prim_mut.items.len == 0) try w.writeAll("0");
        try w.writeAll("};\n");
    }
    for (p.closures.items) |cc| {
        var anc: std.ArrayList(u32) = .empty;
        if (functionClass(p, cc.arity)) |f| {
            try anc.append(p.a, f);
            if (f < p.m.class_ancestors.items.len) for (p.m.class_ancestors.items[f]) |x| {
                if (x.int() != f) try anc.append(p.a, x.int());
            };
        }
        try writeIds(w, "KCA", cc.id, anc.items);
    }
    try w.print("static const klio_r_class KCLASSES[{d}] = {{\n", .{@max(p.classes.items.len + p.closures.items.len, 1)});
    var n: usize = 0;
    for (p.classes.items) |c| {
        if (c >= p.r.classes.len) continue;
        const crt = &p.r.classes[c];
        const def = crt.def.asPtrConst();
        const ic = &p.m.classes.items[c];
        const anc = try ancestorsOf(p, c);
        try w.print("  {{ {d}u, ", .{c});
        try ctype.writeCString(w, ic.name);
        try w.writeAll(", ");
        try ctype.writeCString(w, ic.fqn);
        try w.print(", {d}u, {d}u, KCN_{d}, KCS_{d}, {d}u, KCA_{d}, {d}u, KCAN_{d}, {d}u, KCP_{d}, KCPM_{d}, {d}u }},\n", .{
            classFlags(def), crt.seeds.len, c, c, anc.ids.len, c, anc.names.len, c, def.primary_params.len, c, c, crt.host_slot,
        });
        n += 1;
    }
    for (p.closures.items) |cc| {
        const fcls = functionClass(p, cc.arity);
        // A closure is the `FunctionN` of its arity to a type test and to
        // `::class`.
        const name, const fqn = if (fcls) |f| .{ p.m.classes.items[f].name, p.m.classes.items[f].fqn } else .{ "Function", "kotlin.Function" };
        var n_anc: usize = 0;
        if (fcls) |f| {
            n_anc = 1;
            if (f < p.m.class_ancestors.items.len) for (p.m.class_ancestors.items[f]) |x| {
                if (x.int() != f) n_anc += 1;
            };
        }
        try w.print("  {{ {d}u, ", .{cc.id});
        try ctype.writeCString(w, name);
        try w.writeAll(", ");
        try ctype.writeCString(w, fqn);
        try w.print(", {d}u, {d}u, 0, 0, {d}u, KCA_{d}, 0u, 0, 0u, 0, 0, {d}u }},\n", .{ rt.Flags.anonymous, cc.n_caps, n_anc, cc.id, NONE });
        n += 1;
    }
    if (n == 0) try w.writeAll("  { 0 }\n");
    try w.writeAll("};\n\n");
}

const Ancestors = struct { ids: []const u32, names: []const []const u8 };

/// Every supertype of `c` but `c`, with the names and FQNs the host's
/// by-name subtype tests read.
fn ancestorsOf(p: *Program, c: u32) Error!Ancestors {
    var ids: std.ArrayList(u32) = .empty;
    var names: std.ArrayList([]const u8) = .empty;
    if (c < p.m.class_ancestors.items.len) for (p.m.class_ancestors.items[c]) |x| {
        if (x.int() == c) continue;
        try ids.append(p.a, x.int());
        if (x.int() < p.m.classes.items.len) {
            const ac = &p.m.classes.items[x.int()];
            try names.append(p.a, ac.name);
            if (!std.mem.eql(u8, ac.fqn, ac.name)) try names.append(p.a, ac.fqn);
        }
    };
    return .{ .ids = ids.items, .names = names.items };
}

fn functionClass(p: *const Program, arity: u32) ?u32 {
    const fns = p.r.host_class.function;
    if (arity >= fns.len) return null;
    return fns[arity].int();
}

fn classFlags(def: anytype) u32 {
    const F = rt.Flags;
    var f: u32 = 0;
    if (def.is_data) f |= F.data;
    if (def.is_value) f |= F.value;
    if (def.is_object) f |= F.object;
    if (def.is_enum) f |= F.enum_;
    if (def.is_sealed) f |= F.sealed;
    if (def.is_interface) f |= F.interface;
    if (def.is_fun_interface) f |= F.fun_interface;
    if (def.is_open) f |= F.open;
    if (def.is_abstract) f |= F.abstract;
    if (def.is_inner) f |= F.inner;
    if (def.is_anonymous) f |= F.anonymous;
    if (def.is_annotation) f |= F.annotation;
    return f;
}

fn writeNameList(w: *Writer, comptime prefix: []const u8, id: u32, names: []const []const u8) Error!void {
    try w.print("static const char *const {s}_{d}[] = {{", .{ prefix, id });
    for (names, 0..) |s, i| {
        if (i != 0) try w.writeAll(", ");
        try ctype.writeCString(w, s);
    }
    if (names.len == 0) try w.writeAll("0");
    try w.writeAll("};\n");
}

fn writeIds(w: *Writer, comptime prefix: []const u8, id: u32, ids: []const u32) Error!void {
    try w.print("static const uint32_t {s}_{d}[] = {{", .{ prefix, id });
    for (ids, 0..) |x, i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}u", .{x});
    }
    if (ids.len == 0) try w.writeAll("0");
    try w.writeAll("};\n");
}

fn writeU32s(w: *Writer, name: []const u8, ids: []const u32) Error!void {
    try w.print("static const uint32_t {s}[] = {{", .{name});
    for (ids, 0..) |x, i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}u", .{x});
    }
    if (ids.len == 0) try w.writeAll("0");
    try w.writeAll("};\n");
}

fn optId(c: ?ClassId) u32 {
    return if (c) |x| x.int() else NONE;
}

fn optSlot(s: ?MethodSlotId) u32 {
    return if (s) |x| x.int() else NONE;
}

/// The natives, the callbacks and their dispatch, the host value kinds'
/// classes and the exceptions: what the runtime builds its module from.
fn writeProgram(p: *Program, w: *Writer, cbs: *const Callbacks) Error!void {
    // Natives, as the program numbers them.
    try w.print("static const klio_r_native KNATIVES[{d}] = {{\n", .{@max(p.rc.natives.items.len, 1)});
    for (p.rc.natives.items) |nid| {
        const n = p.r.natives[nid.int()];
        if (n.op != .none and n.op != .print_err) p.refuse("the compiler intrinsic `{s}`", .{n.name});
        var flags: u32 = 0;
        if (n.static_) flags |= 1;
        if (n.receiver) flags |= 2;
        try w.writeAll("  { ");
        try ctype.writeCString(w, n.name);
        try w.print(", {d}u, ", .{@as(u32, switch (n.table) {
            .natives => 0,
            .constructors => 1,
            .members => 2,
            .unbound => 3,
            // A fast path fronts a body the program compiles; it is never
            // one of the program's natives.
            .tries => 4,
        })});
        try ctype.writeCString(w, n.key);
        try w.print(", {d}u, {d}u, {d}, {d}u }},\n", .{
            flags, n.reified, if (n.vararg_back) |b| @as(i32, b) else -1, @intFromEnum(n.op),
        });
    }
    if (p.rc.natives.items.len == 0) try w.writeAll("  { 0 }\n");
    try w.writeAll("};\n");

    try w.print("static const klio_r_function KFUNCTIONS[{d}] = {{\n", .{@max(cbs.entries.items.len, 1)});
    for (cbs.entries.items, 0..) |cb, i| switch (cb) {
        .native => |n| try w.print("  {{ 0, {d}u, 0u }},\n", .{p.nativeIndex(n)}),
        .compiled => |f| try w.print("  {{ kw_{d}, 0u, {d}u }},\n", .{ i, p.body(f).?.sig.params.len }),
        .invoke => |arity| try w.print("  {{ kw_{d}, 0u, {d}u }},\n", .{ i, arity + 1 }),
        .closure => |c| try w.print("  {{ kw_{d}, 0u, {d}u }},\n", .{ i, @as(u32, if (c.which == .equals) 2 else 1) }),
    };
    if (cbs.entries.items.len == 0) try w.writeAll("  { 0 }\n");
    try w.writeAll("};\n");
    try w.print("static const klio_r_dispatch KDISPATCH[{d}] = {{\n", .{@max(cbs.dispatch.items.len, 1)});
    for (cbs.dispatch.items) |d| try w.print("  {{ {d}u, {d}u, {d}u }},\n", .{ d.cls, d.slot, d.entry });
    if (cbs.dispatch.items.len == 0) try w.writeAll("  { 0 }\n");
    try w.writeAll("};\n");
    var wks: std.ArrayList(u32) = .empty;
    for (p.r.well_known.values) |wk| try wks.append(p.a, optSlot(wk));
    try writeU32s(w, "KWELLKNOWN", wks.items);
    if (cbs.match_groups) |mg| {
        try w.print("static const klio_r_raised KMATCHGROUPS = {{ 0, {d}u, {d}u }};\n", .{ mg.class.int(), entryIndex(cbs, .{ .compiled = mg.ctor }) });
    } else try w.print("static const klio_r_raised KMATCHGROUPS = {{ 0, {d}u, {d}u }};\n", .{ NONE, NONE });
    try w.print("static const klio_r_raised KRAISED[{d}] = {{\n", .{cbs.fixed.len});
    for (cbs.fixed) |x| {
        if (x) |raised| {
            const entry = entryIndex(cbs, .{ .compiled = raised.ctor });
            try w.print("  {{ 0, {d}u, {d}u }},\n", .{ raised.class.int(), entry });
        } else try w.print("  {{ 0, {d}u, {d}u }},\n", .{ NONE, NONE });
    }
    try w.writeAll("};\n");
    try w.print("static const klio_r_raised KBYFQN[{d}] = {{\n", .{@max(cbs.by_fqn.items.len, 1)});
    for (cbs.by_fqn.items) |hr| {
        try w.writeAll("  { ");
        try ctype.writeCString(w, hr.fqn);
        try w.print(", {d}u, {d}u }},\n", .{ hr.raised.class.int(), entryIndex(cbs, .{ .compiled = hr.raised.ctor }) });
    }
    if (cbs.by_fqn.items.len == 0) try w.writeAll("  { 0 }\n");
    try w.writeAll("};\n");

    // The host value kinds' classes.
    const h = &p.r.host_class;
    const singles = [_]?ClassId{ h.unit, h.boolean, h.char, h.byte, h.short, h.int, h.long, h.float, h.double, h.ubyte, h.ushort, h.uint, h.ulong, h.string, h.array };
    var ids: std.ArrayList(u32) = .empty;
    for (singles) |c| try ids.append(p.a, optId(c));
    try writeU32s(w, "KH_SCALARS", ids.items);
    ids = .empty;
    for (h.by_tag) |c| try ids.append(p.a, optId(c));
    try writeU32s(w, "KH_TAGS", ids.items);
    ids = .empty;
    for (h.prim_array) |c| try ids.append(p.a, optId(c));
    try writeU32s(w, "KH_PRIM", ids.items);
    ids = .empty;
    for (h.range) |c| try ids.append(p.a, optId(c));
    try writeU32s(w, "KH_RANGE", ids.items);
    ids = .empty;
    for (h.progression) |c| try ids.append(p.a, optId(c));
    try writeU32s(w, "KH_PROG", ids.items);
    ids = .empty;
    for (h.function) |c| try ids.append(p.a, c.int());
    try writeU32s(w, "KH_FN", ids.items);
    ids = .empty;
    for (h.invoke_slot) |s| try ids.append(p.a, s.int());
    try writeU32s(w, "KH_INVOKE", ids.items);

    try w.writeAll("KLIO_NORETURN static void kthrow_hook(klio_value v) { kthrow(v); }\n");
    try w.print(
        \\static const klio_r_program KPROGRAM = {{
        \\  KCLASSES, {d}, KFUNCTIONS, {d}, KDISPATCH, {d}, KNATIVES, {d}, KWELLKNOWN, {d},
        \\  KRAISED, {d}, KBYFQN, {d},
        \\  KH_SCALARS, KH_TAGS, {d}, KH_PRIM, {d}, KH_RANGE, KH_PROG, {d}, KH_FN, {d}, KH_INVOKE, {d},
        \\  {d}u, {d}u, {d}u,
        \\  KMATCHGROUPS,
        \\  kthrow_hook,
        \\}};
        \\
        \\
    , .{
        p.classes.items.len + p.closures.items.len, cbs.entries.items.len, cbs.dispatch.items.len, p.rc.natives.items.len, p.r.well_known.values.len,
        cbs.fixed.len,                              cbs.by_fqn.items.len,
        h.by_tag.len,                               h.prim_array.len,   h.range.len,                 h.function.len,        h.invoke_slot.len,
        optSlot(h.equals_slot),                     optSlot(h.hash_code_slot), optSlot(h.to_string_slot),
    });
}

fn entryIndex(cbs: *const Callbacks, cb: Callback) u32 {
    for (cbs.entries.items, 0..) |e, i| {
        if (std.meta.eql(e, cb)) return @intCast(i);
    }
    return NONE;
}

fn writeMain(p: *Program, w: *Writer) Error!void {
    try w.writeAll("static void kmain(void) {\n  klio_try t; klio_try_arm(&t);\n  if (setjmp(t.jb) != 0) { klio_try_top = 0; klio_r_uncaught(klio_in_flight); }\n");
    const mb = p.body(p.main).?;
    if (p.unitIndex(p.mainUnit())) |ui| try w.print("  if (KU[{d}] != 2) ku_{d}();\n", .{ ui, ui });
    if (mb.sig.params.len == 0) {
        try w.print("  (void)kf_{d}();\n", .{p.main.int()});
    } else {
        const array = p.r.host_class.array orelse {
            p.refuse("`main` takes arguments, and the base declares no `Array`", .{});
            return;
        };
        try w.print("  KROOT[1] = klio_r_new_array({d}u, 0, 0);\n  (void)kf_{d}(KROOT[1]);\n", .{ array.int(), p.main.int() });
    }
    try w.writeAll("  klio_try_pop(&t);\n}\n\n");
    try w.print("int main(void) {{\n  if (klio_r_abi() != UINT64_C(0x{x})) {{ fputs(\"klio: this program was compiled for another klio runtime\\n\", stderr); return 2; }}\n", .{rt.abi});
    try w.writeAll("  klio_nat_init(0);\n  klio_r_describe(&KPROGRAM);\n");
    try w.writeAll("  for (unsigned i = 0; i < sizeof KROOT / sizeof KROOT[0]; i++) KROOT[i] = klio_nat_null();\n");
    for (p.statics.items, 0..) |st, i| {
        const t = sig_mod.seedTy(p.r.statics[st.int()].seed);
        if (t == .object) continue;
        try w.print("  KG[{d}] = ", .{i});
        try ctype.writeBox(w, t, "0");
        try w.writeAll(";\n");
    }
    try w.writeAll("  KROOTF.n = sizeof KROOT / sizeof KROOT[0]; KROOTF.slots = KROOT; klio_nat_enter(&KROOTF);\n");
    // The throwable in flight is rooted while a handler is found for it.
    try w.writeAll("  klio_in_flight = klio_nat_null();\n  static klio_nat_frame KIFF; KIFF.n = 1; KIFF.slots = &klio_in_flight; klio_nat_enter(&KIFF);\n");
    try w.writeAll("  return klio_r_run(kmain);\n}\n");
}
