[package]
name = "klio-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
klio-span        = { workspace = true }
klio-ast         = { workspace = true }
klio-types       = { workspace = true }
klio-runtime     = { workspace = true }
klio-diagnostics = { workspace = true }
serde            = { workspace = true }
