[package]
name = "klio-stdlib-pack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[lints]
workspace = true

[dependencies]
klio-pack = { workspace = true }

[dev-dependencies]
klio-stdlib = { workspace = true }

[build-dependencies]
klio-stdlib = { workspace = true }
