[package]
name = "klio-interp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
klio-span        = { workspace = true }
klio-diagnostics = { workspace = true }
klio-ast         = { workspace = true }
klio-runtime     = { workspace = true }
klio-stdlib      = { workspace = true }
klio-pack        = { workspace = true }
klio-types       = { workspace = true }

[dev-dependencies]
klio-lexer       = { workspace = true }
klio-parser      = { workspace = true }
criterion        = { workspace = true }

[[bench]]
name = "eval"
harness = false

[[bench]]
name = "single_op"
harness = false

[lints]
workspace = true
