[package]
name = "ktc-interp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ktc-span        = { workspace = true }
ktc-diagnostics = { workspace = true }
ktc-ast         = { workspace = true }
ktc-runtime     = { workspace = true }
ktc-stdlib      = { workspace = true }

[dev-dependencies]
ktc-lexer       = { workspace = true }
ktc-parser      = { workspace = true }

[lints]
workspace = true
