//! The stdlib source manifest: which Kotlin files the stdlib pack is built
//! from and where they live in the repo. Dependency-free on purpose so the
//! top-level build.zig can import it directly and declare the same files as
//! inputs of the build-time pack embed step. `pack_builder.zig` re-exports
//! everything here for runtime consumers.

/// Curated set of upstream stdlib commonMain `.kt` files the embedded stdlib
/// pack ships verbatim as a `SOURCES` section, so the interpreter consumes
/// the real upstream Kotlin instead of (or alongside) the mined surface.
///
/// Each entry is a path relative to `kotlin/libraries/stdlib` in the local
/// upstream Kotlin checkout.
pub const CURATED_UPSTREAM_SOURCES = [_][]const u8{
    "src/kotlin/time/Duration.kt",
    "src/kotlin/time/DurationUnit.kt",
    "src/kotlin/time/longSaturatedMath.kt",
    "src/kotlin/time/measureTime.kt",
    "src/kotlin/time/TimeSource.kt",
    "src/kotlin/time/TimeSources.kt",
    "src/kotlin/time/Clock.kt",
    "src/kotlin/time/Clocks.kt",
    "src/kotlin/time/Instant.kt",
    "src/kotlin/time/ExperimentalTime.kt",
    "src/kotlin/coroutines/CoroutineContext.kt",
    "src/kotlin/coroutines/CoroutineContextImpl.kt",
    "src/kotlin/coroutines/ContinuationInterceptor.kt",
    "src/kotlin/coroutines/Continuation.kt",
    "common/src/generated/_Strings.kt",
    "common/src/generated/_Maps.kt",
    "common/src/generated/_Collections.kt",
    "common/src/generated/_Sets.kt",
    "common/src/generated/_Ranges.kt",
    "common/src/generated/_Sequences.kt",
    "common/src/kotlin/Comparator.kt",
    "src/kotlin/util/Standard.kt",
    "src/kotlin/util/Tuples.kt",
    "src/kotlin/util/Result.kt",
    "src/kotlin/util/Numbers.kt",
    "src/kotlin/util/Lateinit.kt",
    "src/kotlin/util/FloorDivMod.kt",
    "src/kotlin/util/Suspend.kt",
    "src/kotlin/util/DeepRecursive.kt",
    "src/kotlin/util/HashCode.kt",
    "src/kotlin/util/Preconditions.kt",
    "src/kotlin/collections/AbstractCollection.kt",
    "src/kotlin/collections/AbstractList.kt",
    "src/kotlin/collections/AbstractMap.kt",
    "src/kotlin/collections/AbstractSet.kt",
    "src/kotlin/collections/Collections.kt",
    "src/kotlin/collections/Iterables.kt",
    "src/kotlin/collections/Maps.kt",
    "src/kotlin/collections/Iterators.kt",
    "src/kotlin/collections/MapAccessors.kt",
    "src/kotlin/collections/SlidingWindow.kt",
    "src/kotlin/collections/MutableCollections.kt",
    "src/kotlin/collections/ReversedViews.kt",
    "src/kotlin/collections/Grouping.kt",
    "src/kotlin/collections/IndexedValue.kt",
    "src/kotlin/collections/MapWithDefault.kt",
    "src/kotlin/collections/Sequence.kt",
    "src/kotlin/collections/SequenceBuilder.kt",
    "src/kotlin/collections/Sets.kt",
    "src/kotlin/comparisons/Comparisons.kt",
    "src/kotlin/comparisons/compareTo.kt",
    "src/kotlin/annotations/OptIn.kt",
    "src/kotlin/annotations/Multiplatform.kt",
    "src/kotlin/annotations/ExperimentalStdlibApi.kt",
    "src/kotlin/annotations/Inference.kt",
    "src/kotlin/annotations/Throws.kt",
    "src/kotlin/annotations/WasExperimental.kt",
    "src/kotlin/annotations/ReturnValue.kt",
    "src/kotlin/annotations/ConsistentCopyVisibility.kt",
    "src/kotlin/annotations/VersionOverloads.kt",
    "src/kotlin/properties/Interfaces.kt",
    "src/kotlin/properties/ObservableProperty.kt",
    "src/kotlin/properties/PropertyReferenceDelegates.kt",
    "src/kotlin/text/CharacterCodingException.kt",
    "src/kotlin/io/encoding/ExperimentalEncodingApi.kt",
    "src/kotlin/uuid/ExperimentalUuidApi.kt",
    "src/kotlin/experimental/ExperimentalNativeApi.kt",
    "src/kotlin/concurrent/Volatile.kt",
    "src/kotlin/concurrent/atomics/ExperimentalAtomicApi.kt",
    "src/kotlin/contextParameters/ExperimentalContextParameters.kt",
    "src/kotlin/ranges/Range.kt",
    "src/kotlin/ranges/Ranges.kt",
    "src/kotlin/ranges/Progressions.kt",
    "src/kotlin/ranges/ProgressionIterators.kt",
    "src/kotlin/AutoCloseable.kt",
    "src/kotlin/contextParameters/Context.kt",
    "src/kotlin/contextParameters/ContextOf.kt",
    "src/kotlin/properties/Delegates.kt",
    "src/kotlin/Function.kt",
    "src/kotlin/random/URandom.kt",
    "src/kotlin/enums/EnumEntries.kt",
    "src/kotlin/Library.kt",
    "src/kotlin/uuid/Uuid.kt",
    "src/kotlin/Unit.kt",
    "src/kotlin/Throwable.kt",
    "src/kotlin/text/regex/MatchResult.kt",
    "src/kotlin/text/regex/RegexExtensions.kt",
    "src/kotlin/CharCode.kt",
    "src/kotlin/Boolean.kt",
    "src/kotlin/Nothing.kt",
    "src/kotlin/Enum.kt",
    "src/kotlin/Number.kt",
    "src/kotlin/Comparable.kt",
    "src/kotlin/Iterator.kt",
    "src/kotlin/CharSequence.kt",
    "src/kotlin/Any.kt",
    "src/kotlin/experimental/ExpectRefinement.kt",
    "src/kotlin/experimental/ExperimentalObjCEnum.kt",
    "src/kotlin/experimental/ExperimentalObjCName.kt",
    "src/kotlin/experimental/ExperimentalObjCRefinement.kt",
    "src/kotlin/reflect/KVariance.kt",
    "src/kotlin/reflect/KTypeProjection.kt",
    "src/kotlin/reflect/KClassifier.kt",
    "src/kotlin/reflect/KTypeParameter.kt",
    "src/kotlin/reflect/KType.kt",
    "src/kotlin/reflect/KCallable.kt",
    "src/kotlin/reflect/KFunction.kt",
    "src/kotlin/reflect/KProperty.kt",
    "src/kotlin/reflect/KClass.kt",
    "src/kotlin/reflect/KClasses.kt",
    "src/kotlin/reflect/typeOf.kt",
    "src/kotlin/Array.kt",
    "src/kotlin/Collections.kt",
    "src/kotlin/String.kt",
    "src/kotlin/Char.kt",
    "src/kotlin/Arrays.kt",
    "src/kotlin/ArrayIntrinsics.kt",
    "common/src/generated/_OneToManyTitlecaseMappings.kt",
    "common/src/generated/_Comparisons.kt",
    "common/src/generated/_UCollections.kt",
    "common/src/generated/_UComparisons.kt",
    "common/src/generated/_URanges.kt",
    "common/src/generated/_USequences.kt",
    "common/src/generated/_Arrays.kt",
    "common/src/generated/_UArrays.kt",
    "common/src/kotlin/ExceptionsH.kt",
    "common/src/kotlin/MathH.kt",
    "common/src/kotlin/TextH.kt",
    "common/src/kotlin/SequencesH.kt",
    "common/src/kotlin/collections/CollectionsH.kt",
    "src/kotlin/coroutines/cancellation/CancellationExceptionH.kt",
    "src/kotlin/collections/ArrayDeque.kt",
    "src/kotlin/collections/UArraySorting.kt",
    "src/kotlin/collections/Sequences.kt",
    "src/kotlin/ranges/PrimitiveRanges.kt",
    "unsigned/src/kotlin/UProgressionUtil.kt",
    "unsigned/src/kotlin/UIntRange.kt",
    "unsigned/src/kotlin/ULongRange.kt",
    "unsigned/src/kotlin/UMath.kt",
    // The unsigned value-class declarations. Execution stays host-repr
    // end to end: the `kotlin.U*` constructor intrinsics reinterpret the
    // signed payload as the host value (so the companion constants and
    // the source bodies' `UInt(...)` wraps never build an interpreted
    // instance), and `data`/`storage` reads on host values are served by
    // the host field path.
    "unsigned/src/kotlin/UnsignedCommon.kt",
    "unsigned/src/kotlin/UByte.kt",
    "unsigned/src/kotlin/UShort.kt",
    "unsigned/src/kotlin/UInt.kt",
    "unsigned/src/kotlin/ULong.kt",
    "unsigned/src/kotlin/UByteArray.kt",
    "unsigned/src/kotlin/UShortArray.kt",
    "unsigned/src/kotlin/UIntArray.kt",
    "unsigned/src/kotlin/ULongArray.kt",
    "src/kotlin/util/KotlinVersion.kt",
    "src/kotlin/collections/PrimitiveIterators.kt",
    "src/kotlin/collections/Arrays.kt",
    "common/src/kotlin/JsAnnotationsH.kt",
    "common/src/kotlin/JvmAnnotationsH.kt",
    "src/kotlin/annotations/NativeAnnotations.kt",
    "src/kotlin/annotations/NativeConcurrentAnnotations.kt",
    // kotlin.concurrent.atomics: the common `expect`s carry the size+init
    // factories; the klio-authored `actual`s (KLIO_STDLIB_ACTUAL_FILES) carry
    // the cell/array-backing class shapes with thread-correct CAS-loop inline
    // extensions. Non-inline RMW methods are made atomic by host bindings
    // (see implementations/atomics.zig).
    "src/kotlin/concurrent/atomics/Atomics.common.kt",
    "src/kotlin/concurrent/atomics/AtomicArrays.common.kt",
    "src/kotlin/util/Lazy.kt",
    "common/src/kotlin/KotlinH.kt",
    "common/src/kotlin/ioH.kt",
    "src/kotlin/text/StringBuilder.kt",
    "src/kotlin/text/HexExtensions.kt",
    "src/kotlin/text/UHexExtensions.kt",
    "src/kotlin/io/encoding/Base64.kt",
    "src/kotlin/coroutines/CoroutinesH.kt",
    "src/kotlin/coroutines/CoroutinesIntrinsicsH.kt",
    "src/kotlin/coroutines/intrinsics/Intrinsics.kt",
    "common/src/kotlin/collections/AbstractMutableCollection.kt",
    "common/src/kotlin/collections/AbstractMutableList.kt",
    "common/src/kotlin/collections/AbstractMutableMap.kt",
    "common/src/kotlin/collections/AbstractMutableSet.kt",
    "common/src/kotlin/collections/ArrayList.kt",
    "common/src/kotlin/collections/HashMap.kt",
    "common/src/kotlin/collections/HashSet.kt",
    "common/src/kotlin/collections/LinkedHashMap.kt",
    "common/src/kotlin/collections/LinkedHashSet.kt",
    "src/kotlin/Primitives.kt",
    "src/kotlin/random/Random.kt",
    "src/kotlin/random/XorWowRandom.kt",
    "src/kotlin/text/HexFormat.kt",
    "native-wasm/src/kotlin/text/CharCategory.kt",
    "src/kotlin/collections/AbstractIterator.kt",
    "src/kotlin/text/Appendable.kt",
    "src/kotlin/text/Char.kt",
    "src/kotlin/text/StringNumberConversions.kt",
    "src/kotlin/text/Strings.kt",
    "src/kotlin/text/Indent.kt",
    "src/kotlin/text/Typography.kt",
    "src/kotlin/contracts/ContractBuilder.kt",
    "src/kotlin/contracts/Effect.kt",
    "src/kotlin/annotation/Annotations.kt",
    "src/kotlin/Annotation.kt",
    "src/kotlin/Annotations.kt",
    "src/kotlin/internal/Annotations.kt",
    "src/kotlin/internal/AnnotationsBuiltin.kt",
    "src/kotlin/internal/progressionUtil.kt",
    "src/kotlin/internal/serializationUtil.kt",
    "src/kotlin/experimental/bitwiseOperations.kt",
    "src/kotlin/experimental/inferenceMarker.kt",
};

/// klio-authored platform `actual` source files shipped in the same `SOURCES`
/// section, paths relative to the `kotlin-klio` directory.
pub const KLIO_STDLIB_ACTUAL_FILES = [_][]const u8{
    "kotlin-time/Actuals.kt",
    "kotlin-coroutines/Actuals.kt",
    "kotlin-coroutines/Intrinsics.kt",
    "kotlin-collections/CollectionsActuals.kt",
    "kotlin-collections/PlatformFactories.kt",
    "kotlin-collections/AbstractMutableCollection.kt",
    "kotlin-collections/AbstractMutableList.kt",
    "kotlin-collections/AbstractMutableSet.kt",
    "kotlin-collections/AbstractMutableMap.kt",
    "kotlin-collections/SequencesActuals.kt",
    "kotlin-comparisons/ComparisonsActuals.kt",
    "kotlin-io/Closeable.kt",
    "kotlin-io/Console.kt",
    "kotlin-io/Serializable.kt",
    "kotlin-io/encoding/Base64Actuals.kt",
    "kotlin-internal/SerializationActuals.kt",
    "kotlin-internal/ConcurrentActuals.kt",
    "kotlin-concurrent/AtomicsActuals.kt",
    "kotlin-concurrent/AtomicArraysActuals.kt",
    "kotlin-util/LazyActuals.kt",
    "kotlin-random/RandomActuals.kt",
    "kotlin-text/TextActuals.kt",
    "kotlin-collections/MapActuals.kt",
    "kotlin-uuid/UuidActuals.kt",
    "kotlin-reflect/ReflectActuals.kt",
};

/// The local upstream Kotlin checkout's `libraries/stdlib` directory, relative
/// to the workspace root (the process cwd when the pack is built).
pub const UPSTREAM_STDLIB_ROOT = "kotlin/libraries/stdlib";
/// The `kotlin-klio` directory holding the klio-authored actuals.
pub const KLIO_STDLIB_DIR = "kotlin-klio";

/// The pinned upstream Kotlin release. The in-tree stdlib source carries a
/// placeholder patch component (`KotlinVersion(major, minor, 255)`) that
/// kotlinc's own build rewrites to the release version; the pack builder
/// applies the same rewrite so `KotlinVersion.CURRENT` matches kotlinc.
pub const KOTLIN_RELEASE = .{ .major = 2, .minor = 4, .patch = 0 };
/// The placeholder expression as it appears in
/// `src/kotlin/util/KotlinVersion.kt`, and the release value it becomes.
pub const KOTLIN_VERSION_FILE = "src/kotlin/util/KotlinVersion.kt";
pub const KOTLIN_VERSION_PLACEHOLDER = std.fmt.comptimePrint(
    "KotlinVersion({d}, {d}, 255)",
    .{ KOTLIN_RELEASE.major, KOTLIN_RELEASE.minor },
);
pub const KOTLIN_VERSION_STAMPED = std.fmt.comptimePrint(
    "KotlinVersion({d}, {d}, {d})",
    .{ KOTLIN_RELEASE.major, KOTLIN_RELEASE.minor, KOTLIN_RELEASE.patch },
);

const std = @import("std");
