[package]
name = "klio-cfa"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
klio-span  = { workspace = true }
klio-ast   = { workspace = true }
klio-types = { workspace = true }

[dev-dependencies]
insta        = { workspace = true }
klio-lexer   = { workspace = true }
klio-parser  = { workspace = true }
klio-diagnostics = { workspace = true }

[lints]
workspace = true
