[package]
name = "ktc-lexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ktc-span        = { workspace = true }
ktc-diagnostics = { workspace = true }
unicode-xid     = { workspace = true }

[dev-dependencies]
insta           = { workspace = true }

[lints]
workspace = true
