[library]
id = "kotlinx.coroutines"
version = "1.11.0"
abi = 1
implicit_packages = []
source_roots = ["shim"]

[[deps]]
id = "stdlib"

[bindings]
"kotlinx.coroutines.__kxco_delayMillis" = "kotlinx.coroutines.__kxco_delayMillis"
