[package]
name = "klio-kotlinx-datetime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
klio-stdlib  = { workspace = true }
klio-runtime = { workspace = true }
chrono       = { version = "0.4", default-features = false, features = ["clock", "std"] }
chrono-tz    = { version = "0.10", default-features = false }
iana-time-zone = "0.1"
