#!/usr/bin/env python3
"""Generate src/skiko/natives.zig from skiko's commonMain Kotlin and the
klio actuals beside it (kotlin-klio/klio-skiko/klioMain), which declare the
natives skiko keeps in its platform sources (Managed's finalizer, RefCnt's).

Every native of org.jetbrains.skia and org.jetbrains.skiko is declared in
skiko's commonMain as

    @ExternalSymbolName("org_jetbrains_skia_Paint__1nMake")
    private external fun Paint_nMake(): NativePointer

and implemented by the C glue under the same symbol. The table lists each
symbol with its signature, `<return>:<parameters>` in one letter per type:

    P  NativePointer or InteropPointer (a pointer; a Long in Kotlin)
    I  Int      F  Float     Z  Boolean   J  Long
    S  Short    B  Byte      D  Double    V  Unit (returns only)

src/skiko/skiko.zig turns each entry into the host function registered under
the symbol.

Usage: scripts/gen-skiko-natives.py [--check]
  --check  exit 1 when the committed table differs from the sources
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "kotlin-klio/klio-skiko/upstream/skiko/src/commonMain/kotlin")
ACTUALS = os.path.join(ROOT, "kotlin-klio/klio-skiko/klioMain")
OUT = os.path.join(ROOT, "src/skiko/natives.zig")

LETTER = {
    "NativePointer": "P",
    "InteropPointer": "P",
    "Int": "I",
    "Float": "F",
    "Boolean": "Z",
    "Long": "J",
    "Short": "S",
    "Byte": "B",
    "Double": "D",
    "Unit": "V",
}

DECL = re.compile(
    r'@ExternalSymbolName\("(?P<symbol>\w+)"\)'
    r'(?:\s*@\w+(?:\([^)]*\))?)*'
    r'\s*(?:(?:private|internal|public)\s+)?external\s+fun\s+(?P<name>\w+)'
    r'\s*\((?P<params>[^)]*)\)'
    r'(?:\s*:\s*(?P<ret>[\w.]+\??))?',
    re.S,
)


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def signature(path, m):
    params = []
    for p in strip_comments(m.group("params")).split(","):
        p = p.strip()
        if not p:
            continue
        ty = p.split(":", 1)[1].strip()
        if ty not in LETTER:
            sys.exit(f"{path}: {m.group('name')}: no native type for parameter type {ty}")
        params.append(LETTER[ty])
    ret = (m.group("ret") or "Unit").strip()
    if ret not in LETTER:
        sys.exit(f"{path}: {m.group('name')}: no native type for return type {ret}")
    return LETTER[ret] + ":" + "".join(params)


def collect():
    found = {}
    walks = [os.walk(SRC), os.walk(ACTUALS)]
    for dp, _, fs in (entry for walk in walks for entry in walk):
        for f in sorted(fs):
            if not f.endswith(".kt"):
                continue
            path = os.path.join(dp, f)
            text = open(path, encoding="utf-8").read()
            for m in DECL.finditer(text):
                sym = m.group("symbol")
                sig = signature(path, m)
                if sym in found and found[sym] != sig:
                    sys.exit(f"{sym}: declared as {found[sym]} and {sig}")
                found[sym] = sig
    if not found:
        sys.exit(f"no natives under {SRC}: run scripts/init-skiko-submodule.sh")
    return found


def render(found):
    lines = [
        "//! The natives of skiko's commonMain (org.jetbrains.skia, org.jetbrains.skiko)",
        "//! and of the klio actuals beside it (kotlin-klio/klio-skiko/klioMain):",
        "//! each @ExternalSymbolName symbol with its signature, `<return>:<parameters>`",
        "//! in the letters skiko.zig marshals. Generated by scripts/gen-skiko-natives.py",
        "//! from those sources; do not edit.",
        "",
        "pub const Native = struct { symbol: [:0]const u8, sig: []const u8 };",
        "",
        "pub const all = [_]Native{",
    ]
    for sym in sorted(found):
        lines.append(f'    .{{ .symbol = "{sym}", .sig = "{found[sym]}" }},')
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    text = render(collect())
    if "--check" in sys.argv[1:]:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print(f"{os.path.relpath(OUT, ROOT)} is stale: run scripts/gen-skiko-natives.py", file=sys.stderr)
            return 1
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"{os.path.relpath(OUT, ROOT)}: {text.count('.symbol')} natives")
    return 0


if __name__ == "__main__":
    sys.exit(main())
