// Generates src/stdlib/implementations/regex_unicode.zig: the code point tables
// behind the stdlib Regex's `\p{...}` classes, read from the running JDK's
// java.lang.Character so the classes answer as the JVM's java.util.regex does.
//
// Usage (JDK 21):
//   java --add-opens java.base/java.lang=ALL-UNNAMED scripts/GenRegexUnicode.java \
//     > src/stdlib/implementations/regex_unicode.zig
//
// The block and script name maps are private to Character.UnicodeBlock and
// Character.UnicodeScript, hence the --add-opens.

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.function.IntPredicate;

public class GenRegexUnicode {
    static final int MAX = Character.MAX_CODE_POINT;
    static final StringBuilder out = new StringBuilder();

    public static void main(String[] args) throws Exception {
        out.append("//! Generated by scripts/GenRegexUnicode.java from JDK ")
            .append(System.getProperty("java.version"))
            .append("'s java.lang.Character; do not edit.\n")
            .append("//! The tables behind the stdlib Regex's `\\p{...}` classes: general\n")
            .append("//! categories, scripts, blocks and the binary properties java.util.regex\n")
            .append("//! reads. A run table pairs `*_starts` with `*_values`; a set is flat\n")
            .append("//! `[lo, hi, lo, hi, ...]` inclusive pairs.\n\n");

        runTable("category", cp -> Character.getType(cp), "u8");

        List<Character.UnicodeScript> scripts = List.of(Character.UnicodeScript.values());
        runTable("script", cp -> Character.UnicodeScript.of(cp).ordinal(), "u8");
        out.append("pub const script_names = [_][]const u8{\n");
        for (Character.UnicodeScript s : scripts) out.append("    \"").append(s.name()).append("\",\n");
        out.append("};\n\n");
        Field aliasesField = Character.UnicodeScript.class.getDeclaredField("aliases");
        aliasesField.setAccessible(true);
        @SuppressWarnings("unchecked")
        Map<String, Character.UnicodeScript> aliases = new TreeMap<>((Map<String, Character.UnicodeScript>) aliasesField.get(null));
        out.append("/// Upper-case ISO 15924 codes `UnicodeScript.forName` accepts beside the names.\n");
        out.append("pub const script_aliases = [_]struct { key: []const u8, index: u8 }{\n");
        for (Map.Entry<String, Character.UnicodeScript> e : aliases.entrySet()) {
            out.append("    .{ .key = \"").append(e.getKey()).append("\", .index = ").append(e.getValue().ordinal()).append(" },\n");
        }
        out.append("};\n\n");

        Field mapField = Character.UnicodeBlock.class.getDeclaredField("map");
        mapField.setAccessible(true);
        @SuppressWarnings("unchecked")
        Map<String, Character.UnicodeBlock> blockMap = new TreeMap<>((Map<String, Character.UnicodeBlock>) mapField.get(null));
        List<Character.UnicodeBlock> blocks = new ArrayList<>();
        for (Character.UnicodeBlock b : blockMap.values()) if (!blocks.contains(b)) blocks.add(b);
        blocks.sort((a, b) -> firstCodePoint(a) - firstCodePoint(b));
        runTable("block", cp -> {
            Character.UnicodeBlock b = Character.UnicodeBlock.of(cp);
            return b == null ? 0xFFFF : blocks.indexOf(b);
        }, "u16");
        out.append("/// Every upper-case key `UnicodeBlock.forName` accepts, with its block index.\n");
        out.append("pub const block_keys = [_]struct { key: []const u8, index: u16 }{\n");
        for (Map.Entry<String, Character.UnicodeBlock> e : blockMap.entrySet()) {
            out.append("    .{ .key = \"").append(e.getKey()).append("\", .index = ").append(blocks.indexOf(e.getValue())).append(" },\n");
        }
        out.append("};\n\n");

        set("alphabetic", Character::isAlphabetic);
        set("ideographic", Character::isIdeographic);
        set("lowercase", Character::isLowerCase);
        set("uppercase", Character::isUpperCase);
        set("mirrored", Character::isMirrored);
        set("java_identifier_start", Character::isJavaIdentifierStart);
        set("java_identifier_part", Character::isJavaIdentifierPart);
        set("unicode_identifier_start", Character::isUnicodeIdentifierStart);
        set("unicode_identifier_part", Character::isUnicodeIdentifierPart);
        set("identifier_ignorable", Character::isIdentifierIgnorable);
        set("emoji", Character::isEmoji);
        set("emoji_presentation", Character::isEmojiPresentation);
        set("emoji_modifier", Character::isEmojiModifier);
        set("emoji_modifier_base", Character::isEmojiModifierBase);
        set("emoji_component", Character::isEmojiComponent);
        set("extended_pictographic", Character::isExtendedPictographic);

        System.out.print(out);
    }

    static int firstCodePoint(Character.UnicodeBlock b) {
        for (int cp = 0; cp <= MAX; cp++) if (Character.UnicodeBlock.of(cp) == b) return cp;
        return Integer.MAX_VALUE;
    }

    interface IntFn { int apply(int cp); }

    static void runTable(String name, IntFn fn, String valueType) {
        List<int[]> runs = new ArrayList<>();
        int prev = Integer.MIN_VALUE;
        for (int cp = 0; cp <= MAX; cp++) {
            int v = fn.apply(cp);
            if (v != prev) {
                runs.add(new int[] { cp, v });
                prev = v;
            }
        }
        out.append("pub const ").append(name).append("_starts = [_]u32{");
        emit(runs, 0);
        out.append("};\n");
        out.append("pub const ").append(name).append("_values = [_]").append(valueType).append("{");
        emit(runs, 1);
        out.append("};\n\n");
    }

    static void set(String name, IntPredicate p) {
        List<int[]> pairs = new ArrayList<>();
        int lo = -1;
        for (int cp = 0; cp <= MAX + 1; cp++) {
            boolean in = cp <= MAX && p.test(cp);
            if (in && lo < 0) lo = cp;
            if (!in && lo >= 0) {
                pairs.add(new int[] { lo });
                pairs.add(new int[] { cp - 1 });
                lo = -1;
            }
        }
        out.append("pub const ").append(name).append(" = [_]u32{");
        emit(pairs, 0);
        out.append("};\n\n");
    }

    static void emit(List<int[]> rows, int col) {
        for (int i = 0; i < rows.size(); i++) {
            if (i % 16 == 0) out.append("\n    ");
            else out.append(' ');
            out.append(rows.get(i)[col]).append(',');
        }
        out.append('\n');
    }
}
