[package]
name = "klio-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
klio-span        = { workspace = true }
klio-ast         = { workspace = true }
klio-diagnostics = { workspace = true }
thiserror       = { workspace = true }
serde           = { workspace = true }

[lints]
workspace = true
