/* klio_rt — the C ABI of the klio Kotlin runtime: program bootstrap plus
 * the per-op helpers transpiled C calls (`klio transpile`). Link against
 * libklio_rt.a (zig build klio-rt). */
#ifndef KLIO_RT_H
#define KLIO_RT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Runs the Kotlin program at `path` exactly as `klio run <path>` would.
 * Returns the process exit code (0 success, nonzero on diagnostics or a
 * runtime error). */
int klio_rt_run_file(const char *path);

/* Runs the Kotlin program at `path` against the pre-baked dependency base
 * at `base_image`, exactly as `klio run-image` would. Transpiled programs
 * use this entry: their emitted ids are only meaningful against the module
 * assembled from that exact artifact. */
int klio_rt_run_image(const char *base_image, const char *path);

/* The hot-view layout descriptor: Value byte offsets measured against
 * the running library at startup, so generated inline scalar ops are
 * correct by construction. `usable == 0` means the process reclaim mode
 * requires the per-op helpers instead. */
typedef struct {
  uint32_t value_size, tag_off, tag_size, int_off, long_off, bool_off;
  uint64_t tag_int, tag_long, tag_bool, tag_unit;
  uint8_t usable;
  /* Frame cur_span (?Span) layout for the inlined trace store;
   * span_usable == 0 keeps traces on the klio_op_trace helper. */
  uint8_t span_usable;
  uint32_t span_file_off, span_start_off, span_end_off, span_tag_off;
  uint8_t span_tag_set;
  /* Char payload location + tag, for fused loops over Char scalars. */
  uint32_t char_off;
  uint64_t tag_char;
  /* Object view: enough of the Instance layout for an inline stored-field
     read behind a class guard. obj_usable == 0 keeps field reads on the
     escape helper. */
  uint8_t obj_usable;
  uint64_t tag_instance;
  uint32_t inst_ptr_off;
  uint32_t cell_data_off;
  uint32_t inst_class_off;
  uint32_t inst_fields_off;
  uint32_t fields_ptr_off;
  uint32_t fields_len_off;
  uint32_t field_stride;
  uint32_t field_value_off;
  /* Array view: an IntArray element read. arr_prim_int_word is the probed
     byte pattern that means "primitive Int storage". */
  uint64_t tag_array;
  uint32_t arr_cell_off;
  uint32_t arr_prim_off;
  uint64_t arr_prim_int_word;
  uint32_t primbuf_ptr_off;
  uint32_t primbuf_len_off;
} klio_hot_layout;
void klio_rt_hot_layout(klio_hot_layout *out);

/* The frame flag/counter addresses the emitted C polls to inline the
 * fused edge guard; fetched per activation entry (threadlocal state).
 * klio_op_edge_rare runs the guard's slow work for the fired triggers:
 * bit0 counter cadence, bit1 abandon, bit2 gc pending, bit3 stress,
 * bit4 idle cadence. */
typedef struct {
  uint64_t *counter;
  uint64_t *idle;
  const uint8_t *abandonable;
  const uint8_t *rb_abandon;
  const uint8_t *abandon_req;
  const uint8_t *gc_pending;
  uint8_t gc_on;
  uint8_t always;
} klio_edge_view;
void klio_op_edge_view(void *ctx, klio_edge_view *out);
int32_t klio_op_edge_rare(void *ctx, uint32_t reasons);

/* The frame's cur_span storage for the inlined trace store. */
uint8_t *klio_op_span_slot(void *ctx);

/* Registers the generated code's layout globals; the run entries fill
 * them after the performance profile (hence the reclaim mode, hence
 * `usable`) is chosen. Call before klio_rt_run_*. */
void klio_rt_register_hot_layout(klio_hot_layout *slot);

/* The library's ABI version (this header describes version 4). */
int klio_rt_abi_version(void);

/* A transpiled function body: runs the function's blocks starting at
 * `entry_block` against the opaque activation context. Generated by
 * `klio transpile`; not meant to be hand-written. */
typedef void (*klio_native_fn)(void *ctx, uint32_t entry_block);

/* Registers a transpiled body for the function id `fid`; the interpreter
 * then runs it in place of its bytecode. Call before klio_rt_run_file —
 * the table is read-only once the program runs. `fqn` (the function's
 * fully qualified name, as emitted) guards the fid: a mismatched entry is
 * ignored, falling back to interpretation rather than running the wrong
 * body. */
void klio_rt_register_native(uint32_t fid, klio_native_fn f, const char *fqn);

/* Declares the func/const table sizes of the module the emitter walked;
 * a frame whose module disagrees runs interpreted (the emitted ids index
 * these tables and mean nothing against any other module). Generated
 * code calls this before registering function bodies. */
void klio_rt_register_module_check(uint64_t n_funcs, uint64_t n_consts);

/* Per-op helpers — the interpreter's own op bodies behind the C ABI.
 * `ctx` is the opaque activation context a native fn was invoked with.
 * Helpers returning int32_t follow one contract: 0 = continue in the
 * emitted code; nonzero = the emitted function must return immediately
 * (the outcome has been recorded on the context). The branch helpers
 * (klio_op_br / klio_op_cmp_br) instead return 1 = take the true edge,
 * 0 = take the false edge, 2 = return immediately. */
/* The activation's register file for the generated inline scalar ops
 * (stable for the whole activation). */
uint8_t *klio_op_regs(void *ctx);
void    klio_op_trace(void *ctx, uint32_t file, uint32_t start, uint32_t end);
int32_t klio_op_const_load(void *ctx, uint32_t dst, uint32_t const_id);
void    klio_op_const_int(void *ctx, uint32_t dst, int32_t payload);
void    klio_op_move(void *ctx, uint32_t dst, uint32_t src);
void    klio_op_load_param(void *ctx, uint32_t dst, uint32_t idx);
void    klio_op_cell_get(void *ctx, uint32_t dst, uint32_t cell);
int32_t klio_op_bin(void *ctx, uint32_t block, uint32_t inst_idx, uint32_t kind, uint32_t dst, uint32_t lhs, uint32_t rhs);
int32_t klio_op_escape(void *ctx, uint32_t block, uint32_t inst_idx);
/* Resolve a GetField site to (class identity, stored slot) for the receiver
   currently in its register. 0 means the site is not a plain stored read. */
/* GC write barrier for a cell about to receive a Value store. */
void klio_rt_write_barrier(void *cell);
int32_t klio_op_field_route(void *ctx, uint32_t block, uint32_t inst_idx,
                            uint64_t *cls_out, int32_t *slot_out);
/* The same verdict for a SetField site (from the interpreter's write memo). */
int32_t klio_op_field_write_route(void *ctx, uint32_t block, uint32_t inst_idx,
                                  uint64_t *cls_out, int32_t *slot_out);
int32_t klio_op_call(void *ctx, uint32_t block, uint32_t inst_idx);

/* Scalar-replay leaf body: the whole function over (int64 value, genre)
 * pairs — genres 0 Int, 1 Long, 2 Bool, 3 Unit, 4 Char. Nonzero = result
 * in (*ret, *retg); zero = pure bail, the runtime re-runs the call. */
typedef int32_t (*klio_leaf_fn)(void *ctx, klio_edge_view *ev,
                                const int64_t *argv, const int32_t *argg,
                                int64_t *ret, int32_t *retg, uint32_t depth);
void klio_rt_register_native_leaf(uint32_t fid, klio_leaf_fn f, const char *fqn);
int32_t klio_op_edge(void *ctx);
int32_t klio_op_br(void *ctx, uint32_t block, uint32_t cond);
int32_t klio_op_cmp_br(void *ctx, uint32_t block, uint32_t inst_idx, uint32_t kind, uint32_t dst, uint32_t lhs, uint32_t rhs);
void    klio_op_ret(void *ctx, uint32_t has_val, uint32_t reg);
void    klio_op_term(void *ctx, uint32_t block);
void    klio_op_goto_exit(void *ctx, uint32_t block);

#ifdef __cplusplus
}
#endif

#endif /* KLIO_RT_H */
