/* klio_rt — the C ABI of the klio Kotlin runtime: program bootstrap plus
 * the per-op helpers transpiled C calls (`klio transpile`). Link against
 * libklio_rt.a (zig build klio-rt). */
#ifndef KLIO_RT_H
#define KLIO_RT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Runs the Kotlin program at `path` exactly as `klio run <path>` would.
 * Returns the process exit code (0 success, nonzero on diagnostics or a
 * runtime error). */
int klio_rt_run_file(const char *path);

/* The library's ABI version (this header describes version 2). */
int klio_rt_abi_version(void);

/* A transpiled function body: runs the function's blocks starting at
 * `entry_block` against the opaque activation context. Generated by
 * `klio transpile`; not meant to be hand-written. */
typedef void (*klio_native_fn)(void *ctx, uint32_t entry_block);

/* Registers a transpiled body for the function id `fid`; the interpreter
 * then runs it in place of its bytecode. Call before klio_rt_run_file —
 * the table is read-only once the program runs. `fqn` (the function's
 * fully qualified name, as emitted) guards the fid: a mismatched entry is
 * ignored, falling back to interpretation rather than running the wrong
 * body. */
void klio_rt_register_native(uint32_t fid, klio_native_fn f, const char *fqn);

/* Per-op helpers — the interpreter's own op bodies behind the C ABI.
 * `ctx` is the opaque activation context a native fn was invoked with.
 * Helpers returning int32_t follow one contract: 0 = continue in the
 * emitted code; nonzero = the emitted function must return immediately
 * (the outcome has been recorded on the context). The branch helpers
 * (klio_op_br / klio_op_cmp_br) instead return 1 = take the true edge,
 * 0 = take the false edge, 2 = return immediately. */
void    klio_op_trace(void *ctx, uint32_t file, uint32_t start, uint32_t end);
int32_t klio_op_const_load(void *ctx, uint32_t dst, uint32_t const_id);
void    klio_op_const_int(void *ctx, uint32_t dst, int32_t payload);
void    klio_op_move(void *ctx, uint32_t dst, uint32_t src);
void    klio_op_load_param(void *ctx, uint32_t dst, uint32_t idx);
void    klio_op_cell_get(void *ctx, uint32_t dst, uint32_t cell);
int32_t klio_op_bin(void *ctx, uint32_t block, uint32_t inst_idx, uint32_t kind, uint32_t dst, uint32_t lhs, uint32_t rhs);
int32_t klio_op_escape(void *ctx, uint32_t block, uint32_t inst_idx);
int32_t klio_op_call(void *ctx, uint32_t block, uint32_t inst_idx);
int32_t klio_op_edge(void *ctx);
int32_t klio_op_br(void *ctx, uint32_t block, uint32_t cond);
int32_t klio_op_cmp_br(void *ctx, uint32_t block, uint32_t inst_idx, uint32_t kind, uint32_t dst, uint32_t lhs, uint32_t rhs);
void    klio_op_ret(void *ctx, uint32_t has_val, uint32_t reg);
void    klio_op_term(void *ctx, uint32_t block);
void    klio_op_goto_exit(void *ctx, uint32_t block);

#ifdef __cplusplus
}
#endif

#endif /* KLIO_RT_H */
