//! Mines `FirErrors.kt` + `FirErrorsDefaultMessages.kt` from the upstream
//! Kotlin compiler for canonical diagnostic factory IDs, default
//! severities, and message templates. Emits Rust constants into
//! `crates/klio-diagnostics/src/generated/factories.rs`.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct Factory {
    pub name: String,
    pub severity: Severity,
    pub message: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
}

impl Severity {
    #[must_use] 
    pub fn as_rust(self) -> &'static str {
        match self {
            Self::Error => "Severity::Error",
            Self::Warning => "Severity::Warning",
        }
    }
}

/// Parse a `FirErrors.kt`-shaped file. Returns `(name → severity)` for every
/// `val NAME: KtDiagnosticFactoryN<…> = KtDiagnosticFactoryN("NAME", SEVERITY, …)`
/// declaration we recognize.
#[must_use] 
pub fn parse_factories(src: &str) -> BTreeMap<String, Severity> {
    let mut out = BTreeMap::new();
    for line in src.lines() {
        let line = line.trim();
        if !line.starts_with("val ") {
            continue;
        }
        let Some(eq) = line.find('=') else { continue };
        let rhs = line[eq + 1..].trim();
        // Look for KtDiagnosticFactory{0,1,2,3,4}( ... or
        // KtDiagnosticFactoryForDeprecationN(…
        if !rhs.starts_with("KtDiagnosticFactory") {
            continue;
        }
        let Some(open) = rhs.find('(') else { continue };
        let args = &rhs[open + 1..];
        // First arg is "NAME", second is SEVERITY (ERROR/WARNING).
        let Some(quote_start) = args.find('"') else { continue };
        let after_quote = &args[quote_start + 1..];
        let Some(quote_end) = after_quote.find('"') else { continue };
        let name = after_quote[..quote_end].to_string();
        let rest = &after_quote[quote_end + 1..];
        let Some(comma) = rest.find(',') else { continue };
        let sev_token = rest[comma + 1..].trim_start();
        let severity = if sev_token.starts_with("ERROR") {
            Severity::Error
        } else if sev_token.starts_with("WARNING") {
            Severity::Warning
        } else {
            continue;
        };
        out.insert(name, severity);
    }
    out
}

/// Parse the default-messages map. Returns `(name → template)` from every
/// `map.put(NAME, "template", …)` line.
#[must_use] 
pub fn parse_messages(src: &str) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for line in src.lines() {
        let line = line.trim();
        if !line.starts_with("map.put(") {
            continue;
        }
        let after_open = &line["map.put(".len()..];
        let Some(comma) = after_open.find(',') else { continue };
        let name = after_open[..comma].trim().to_string();
        let rest = after_open[comma + 1..].trim_start();
        if !rest.starts_with('"') {
            continue;
        }
        let body = &rest[1..];
        // Find the matching close quote, respecting `\"` escapes.
        let mut end = None;
        let mut prev = '\0';
        for (i, c) in body.char_indices() {
            if c == '"' && prev != '\\' {
                end = Some(i);
                break;
            }
            prev = c;
        }
        let Some(e) = end else { continue };
        let template = body[..e].to_string();
        out.insert(name, template);
    }
    out
}

#[must_use] 
pub fn mine(stdlib_root: &Path) -> Vec<Factory> {
    let fir_errors = stdlib_root.join(
        "compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/diagnostics/FirErrors.kt",
    );
    let fir_messages = stdlib_root.join(
        "compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/FirErrorsDefaultMessages.kt",
    );

    let factories = fs::read_to_string(&fir_errors)
        .map(|s| parse_factories(&s))
        .unwrap_or_default();
    let messages = fs::read_to_string(&fir_messages)
        .map(|s| parse_messages(&s))
        .unwrap_or_default();

    let mut out: Vec<Factory> = factories
        .into_iter()
        .map(|(name, severity)| {
            let message = messages.get(&name).cloned().unwrap_or_else(|| name.clone());
            Factory { name, severity, message }
        })
        .collect();
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

/// Render the generated Rust module.
#[must_use] 
pub fn render(factories: &[Factory]) -> String {
    let mut s = String::new();
    s.push_str("//! Auto-generated by `klio-diagnostics-gen`. Do not edit by hand.\n\n");
    s.push_str("#![allow(non_upper_case_globals)]\n\n");
    s.push_str("use crate::{DiagnosticFactory, Severity};\n\n");
    s.push_str("pub static FACTORIES: &[&DiagnosticFactory] = &[\n");
    for f in factories {
        s.push_str(&format!("    &{},\n", f.name));
    }
    s.push_str("];\n\n");
    for f in factories {
        s.push_str(&format!("pub const {}: DiagnosticFactory = DiagnosticFactory {{\n", f.name));
        s.push_str(&format!("    name: {:?},\n", f.name));
        s.push_str(&format!("    default_severity: {},\n", f.severity.as_rust()));
        s.push_str(&format!("    message_template: {:?},\n", f.message));
        s.push_str("};\n");
    }
    s
}

pub fn emit(factories: &[Factory], out_file: &Path) -> std::io::Result<()> {
    if let Some(parent) = out_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_file, render(factories))
}

#[must_use] 
pub fn default_kotlin_root() -> PathBuf {
    let m = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    m.parent()
        .and_then(|p| p.parent()).map_or_else(|| PathBuf::from("kotlin"), |p| p.join("kotlin"))
}

#[must_use] 
pub fn default_out_file() -> PathBuf {
    let m = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    m.parent()
        .and_then(|p| p.parent()).map_or_else(|| PathBuf::from("crates/klio-diagnostics/src/generated/factories.rs"), |p| p.join("crates/klio-diagnostics/src/generated/factories.rs"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_typical_factory_line() {
        let src = r#"
            val UNSUPPORTED: KtDiagnosticFactory1<String> = KtDiagnosticFactory1("UNSUPPORTED", ERROR, SourceElementPositioningStrategies.DEFAULT, PsiElement::class, getRendererFactory())
            val SHADOWED: KtDiagnosticFactory0 = KtDiagnosticFactory0("SHADOWED", WARNING, SourceElementPositioningStrategies.DEFAULT, PsiElement::class, getRendererFactory())
        "#;
        let m = parse_factories(src);
        assert_eq!(m.get("UNSUPPORTED"), Some(&Severity::Error));
        assert_eq!(m.get("SHADOWED"), Some(&Severity::Warning));
    }

    #[test]
    fn parses_typical_message_line() {
        let src = r#"
            map.put(UNSUPPORTED, "{0}", TO_STRING)
            map.put(OTHER_ERROR, "Unknown error.")
            map.put(NEW_INFERENCE_ERROR, "New inference error [{0}].", STRING)
        "#;
        let m = parse_messages(src);
        assert_eq!(m.get("UNSUPPORTED").map(String::as_str), Some("{0}"));
        assert_eq!(m.get("OTHER_ERROR").map(String::as_str), Some("Unknown error."));
        assert_eq!(m.get("NEW_INFERENCE_ERROR").map(String::as_str), Some("New inference error [{0}]."));
    }
}
