[package]
name = "klio-resolver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
klio-span        = { workspace = true }
klio-ast         = { workspace = true }
klio-diagnostics = { workspace = true }
klio-types       = { workspace = true }
thiserror       = { workspace = true }

[dev-dependencies]
klio-lexer       = { workspace = true }
klio-parser      = { workspace = true }
insta           = { workspace = true }
criterion        = { workspace = true }

[[bench]]
name = "resolve"
harness = false

[lints]
workspace = true
