[package]
name = "ktc-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ktc-span        = { workspace = true }
ktc-ast         = { workspace = true }
ktc-diagnostics = { workspace = true }
thiserror       = { workspace = true }

[lints]
workspace = true
