[package]
name = "klio-stdlib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
klio-runtime = { workspace = true }
unicode-general-category = "1"
regex = "1"

[dev-dependencies]
criterion        = { workspace = true }
klio-lexer       = { workspace = true }
klio-parser      = { workspace = true }
klio-span        = { workspace = true }
klio-interp      = { workspace = true }

[[bench]]
name = "intrinsics"
harness = false

[lints]
workspace = true
